config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  resources :groups
  root 'groups#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :group, optional: true
  
  
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :concerts, :dependent => :destroy
   
    enum bandtype: [:male, :female, :band]

    def to_s 
        name
    end

    
    def total_concerts
        concerts.where(group_id: id).count
    end


    def attendance
        concerts.where(group_id: id).map{|concert| concert.tickets}.sum
    end

    def last_concert
        concerts.where(group_id: id).map{|concert| concert.event.strftime("%Y:%B:%A")}.last
    end

    def max_people
        concerts.pluck(:tickets).max
    end

    def max_duration
        concerts.pluck(:duration).max
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @groups = Group.all
  end

  # GET /concerts/1/edit
  def edit
    @groups = Group.all
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)
    @groups = Group.all

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:event, :tickets, :duration, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
    @concerts = Concert.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  
  end

  # GET /groups/new
  def new
    @group = Group.new
    @concerts = Concert.all
    
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :members, :debut, :bandtype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label">
    <%= form.label :event, "Fecha del Concierto" %>
    <%= form.date_select :event , :start_year => 1980 %>
  </div>

  <div class="field">
    <%= form.label :tickets, "Asistentes" %>
    <%= form.number_field :tickets %>
  </div>

  <div class="field">
    <%= form.label :duration, "Duración en Minutos" %>
    <%= form.number_field :duration %>
  </div>


  <div class="field">
  <%= form.label :group, "Grupo" %>
    <select name="concert[group_id]">
    <% @groups.each do |group| %>
      <option value="<%= group.id %>"><%= group.name %></option> 
    <% end %>
    </select>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Más Info', @concert %> |
<%= link_to 'Volver', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos Los Conciertos</h1>

<table>
  <thead>
    <tr>
      <th>Evento</th>
      <th>Asistencia</th>
      <th>Duración</th>
      <th>Grupo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.event %></td>
        <td><%= concert.tickets %> personas</td>
        <td><%= concert.duration %> minutos</td>
        <td><%= concert.group.name %></td>
        <td><%= link_to 'Más Info', concert %></td>
        <td><%= link_to 'Editar', edit_concert_path(concert) %></td>
        <td><%= link_to 'Borrar', concert, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Volver a Grupos', root_path %><br>
<%= link_to 'Nuevo Concierto', new_concert_path %>

app/views/concerts/new.html.erb
<h3>Nuevo Concierto</h3>

<%= render 'form', concert: @concert %>

<%= link_to 'Volver a Grupos', root_path %>
<%= link_to 'Todos los Conciertos', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha Evento:</strong>
  <%= @concert.event %>
</p>

<p>
  <strong>Asistencia:</strong>
  <%= @concert.tickets %>
</p>

<p>
  <strong>Duración:</strong>
  <%= @concert.duration %> minutos
</p>

<p>
  <strong>Grupo:</strong>
  <%= @concert.group.name %>
</p>

<%= link_to 'Editar', edit_concert_path(@concert) %> |
<%= link_to 'Volver', concerts_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name , "Grupo" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :members , "Cantidad Miembros" %>
    <%= form.number_field :members %>
  </div>

  <div class="field">
    <%= form.label :debut , "Fecha Debut" %>
    <%= form.date_select :debut %>
  </div>

  <div class="field">
    <%= form.label :bandtype , "Tipo de Banda"%>
    <%= form.select :bandtype , Group.bandtypes.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Mostrar', @group %> |
<%= link_to 'Volver', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="text-center">Gestor de Grupos</h2>

<table class="table mt-4">
  <thead class="table-light">
    <tr>
      <th class="text-center">Nombre</th>
      <th class="text-center">Cantidad Miembros</th>
      <th class="text-center">Conciertos</th>
      <th class="text-center">Asistentes Totales</th>
      <th class="text-center">Tipo Banda</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td class="table-warning"><%= group.name %></td>
        <td class="text-center"><%= group.members %></td>
        <td class="text-center"><%= group.total_concerts %></td>
        <td class="text-center"><%= group.attendance %></td>
        <td class="text-center"><%= group.bandtype %></td>
        <td><%= link_to 'Mostrar', group %></td>
        <td><%= link_to 'Editar', edit_group_path(group) %></td>
        <td><%= link_to 'Borrar', group, method: :delete, data: { confirm: 'Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Grupo', new_group_path %><br>
<%= link_to 'Agregar Concierto', new_concert_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Volver', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Nombre del Grupo:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Cantidad de Miembros:</strong>
  <%= @group.members %>
</p>

<p>
  <strong>Último Concierto:</strong>
  <%= @group.last_concert %>
</p>

<p>
  <strong>Mayor Éxito:</strong>
  <%= @group.max_people %> personas
</p>

<p>
  <strong>Concierto Más Extenso:</strong>
  <%= @group.max_duration %>  minutos
</p>

<p>
  <strong>Debut:</strong>
  <%= @group.debut %>
</p>

<p>
  <strong>Tipo de banda:</strong>
  <%= @group.bandtype %>
</p>

<%= link_to 'Editar', edit_group_path(@group) %> |
<%= link_to 'Volver', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcertsWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>